### ISSUE TITLE
Coloring of peptide plot per rank

### ISSUE THREAD

**Issue by plinders** [tercen/upstream_kinase_analysis_shiny_operator#5]
This line seems to solve this issue and should reflect what we have in BioNavigator

https://github.com/tercen/uka_shiny_operator/blob/6ad527d2309fcb1b36652e039bd6caddc0ad2d7c/upstream_output.R#L81

**Comment by ginberg** [comment]
hi @plinders, I made the fix for this issue and for #4 and created a new tag for this operator (0.0.6). Could you have a look at the new version and see if it looks good to you?

**Comment by plinders** [comment]
This looks great! These issues are now solved.
I added some additional feedback to the Google Sheet (unrelated to #4 and #5).
